const tels = [
    'Adorar significa, en el sentido más amplio, cumplir por amor la voluntad de Dios',
    'La alegría debe irradiarse en nuestro propio  rostro',
    'Padre en la simplicidad de mi corazón, te entrego hoy todo con alegría',
    'Nada me quitará la alegría',
    'Creo firmemente que nunca perecerá quien permanece fiel a su Alianza de amor',
    'El amor de Dios es la ley básica universal',
    'No hay nada mejor que el amor, nada más grande que el amor, nada más hermoso que el amor',
    'El amor verdadero no se aísla nunca',
    'El que ama hace lo que le da alegría al amado',
    'Quien quiera conquistar los corazones, debe dar a cambio su propio corazón',
    '¡En la humildad, por debajo de todos!¡En el amor, por encima de todos!',
    'El amor exige amor recíproco, por eso es incansable en pruebas de amor',
    'La verdadera vida consiste en amar',
    '¡El amor lleva y sobrelleva, es arriesgado y reflexivo, el amor vence todo!',
    'Mi profesión principal, mi deber principal y mi oración principal, es y seguirá siendo:  ¡Amar!',
    '¡El amor vive del sufrimiento!',
    '¡Es el sufrimiento quien alimenta y acrisola el amor!',
    'Amor y humildad es estar vinculado y ser libre de sí mismo',
    'La cruz descifra todos los enigmas de la vida',
    'La cruz bendice al mundo',
    'Lleve Usted, su cruz tranquilo, humilde, valiente. ¡Así ayuda Ud. a salvar el mundo!',
    '¡El Padre me ama!',
    '¡El Padre y yo somos uno!',
    '¡Qué hermoso es poder decir que en el plan de Dios todo está previsto desde la eternidad!',
    'Dios  es amor y por eso alegría eterna. Por lo tanto quien vive en Dios o quien quiere reflejarlo, debe ser al mismo tiempo  un reflejo  de la alegría eterna…',
    'Tú sabes que te amo',
    '¡Dios es Padre, Dios es bueno y bueno es todo lo que Él hace!',
    '¡Estoy cobijado en el Padre!',
    'Sus ángeles contemplan permanentemente el rostro del Padre',
    'Cada ser humano es un pensamiento y un deseo de Dios',
    '¡El padre ama y protege a su hijo como la pupila de sus ojos!',
    'Sí, Padre, sí. Que se haga siempre tu voluntad, ya sea que me traiga alegría, sufrimiento o dolor',
    '¡De la mano del Padre hacia la Patria!',
    'Dios gobierna el mundo también cuando pareciera que no se preocupa de él',
    '¡El Padre y yo somos uno!',
    '¡Guíame según tus sabios planes y se cumplirá mi único anhelo!',
    'Hay que arrancar toda fibra del alma que no pertenezca a Dios',
    'El hijo es la riqueza de su Padre',
    'Hoy comenzaré, hoy nuevamente quisiera consagrar toda mi vida al buen Dios',
    '¡Déjame ser tu corona!',
    'Señor, despréndeme de mí mismo: Entonces habrás vencido la batalla en mí',
    '¡El hijo no es nada, el Padre es todo!',
    'A los hijos más pequeños es a quienes más ama el Padre del cielo',
    '¡Ascender con los hombres y por encima de las debilidades humanas al corazón de Dios!',
    '¡Todo lo puedo en aquel que me conforta!',
    '¡Permanezco Hijo!',
    'Nuestro honor puede ser pisoteado, podemos ser triturados y desterrados, sólo Dios tiene que vivir',
    '¡Haced lo que Él os diga!',
    'Debo estar en las cosas de mi ¡Padre!',
    '¡El hijo es la riqueza del Padre cuando aspira al infinitismo de la pequeñez!',
    'Lo que hace el Padre siempre es bueno',
    '¡Caminar siempre, en el corazón del Padre, hacia el cielo!',
    'Quien hace la voluntad de mi Padre, es el que me ama',
    '¡Hago siempre lo que le da alegría al Padre!',
    '¡Amemos profundamente a Dios, el Norte de nuestra vida!',
    'El que desea agradar a Dios, ha de aspirar a la pureza conforme a su estado',
    '¡Enséñame a vivir cada día!',
    'No podemos considerarnos importantes, sólo Dios es importante',
    'Padre, hágase en cada instante lo que para nosotros tienes previsto',
    'Guíanos según tus sabios planes y se cumplirá nuestro único anhelo',
    'El buen Dios me ama a pesar de mi pequeñez, es más, a causa de mi pequeñez y miseria',
    'Si queremos convertirnos, en gran medida, en personas espiritualizadas, debemos estar atentos a lo que Dios nos dice',
    '¡Yo sé que Tú eres mi Padre y que estoy cobijado en tu corazón!',
    'Quien por amor a Dios pierde su vida, la ganará',
    'Es la voluntad e Dios, ¡calla!',
    '¡Todo proviene de la bondad de Dios!',
    'Mi destino y el de los míos, descansa en las manos del Padre',
    'Señor, permíteme servir. Esta es mi mayor recompensa',
    'Tú eres el que realiza las obras más grandes sólo por medio de los más pequeños, Dios ama a los pequeños y puros',
    'Dios es un Dios de la alegría y de la paz',
    'Sí Padre, Sí Madre. Para siempre',
    'El Padre purifica la vid para que dé más fruto',
    'Cuándo más desamparados estemos, tanto mayor debe ser nuestra confianza',
    'odo hombre necesita un nido, pero jamás tendrá total tranquilidad mientras no haya hallado su nido fundamental en el corazón de Dios',
    'Ser héroe es responder siempre: ¡Sí, Padre! A las pequeñas cosas de la vida diaria o para que se cumpla en usted la voluntad de Dios!',
    'Que pueda sufrir en silencio tu voluntad, Señor',
    'El que mantiene siempre abiertos el corazón y los sentidos para lo que le agrada a Dios, permanece joven hasta edad avanzada, porque nunca le falta la fuerza del amor',
    'Ponme la corona de espinas, sáciame con escarnios y burlas, ¡Nunca nada será demasiado difícil para mí cuando de TI  se trate, Señor!',
    'Te pido todas las cruces y sufrimientos que Tú, Padre, me tengas preparados',
    '¡Déjame encontrar Padre, definitivamente el camino del retorno a Ti!',
    '¡Nada pasa por casualidad! todo viene de la bondad de Dios!',
    'Con la bendición del Padre ¡A través de tempestades y tormentas!',
    'Hazme Padre ser un milagro de misericordia, pues soy débil y pequeño',
    'Ser hijo de la Providencia significa estar convencido que cada situación, alegría, sufrimiento desilusión… es una parte esencial del plan de la omnipotencia, de la sabiduría  y el amor de Dios',
    'El misterio de la Divina Providencia permanece muerto cuando sólo reflexionamos sobre él. Se hace realidad cuando lo vivimos',
    'La Divina Providencia es tan sabia y poderosa que es capaz  de construir un majestuoso edificio con escombros',
    'La Divina Providencia tiene todo en su mano, trabaja sabiamente con éxito  infalible, pero a nuestras miradas permanece vedado  cuándo llegará   el éxito previsto',
    'Dios  alcanza su meta cuando llega el instante preciso',
    'La Fe en la Divina Providencia deber ser práctica, no teórica. No ha de ser algo pasivo, sino activa. No espero cruzado de  brazos que suceda lo que el Padre ha previsto en su plan. Sino que debo salir a buscar el plan de Dios para realizarlo',
    '¡Está en el plan!  Cuántas  veces  aparece en la Sagrada Escritura: “Todo esto ha acontecido a fin de que se cumplieran las Escrituras” (Mt. 26,56)',
    'La Fe en la Divina Providencia nos dice que Dios, en su sabiduría, bondad, y poder, ha esbozado, desde la eternidad, un gran plan  del mundo y el plan de nuestra pequeña vida',
    'Debemos escuchar exactamente el mensaje: ¡El plan  de  mi vida es un plan de amor!',
    'La escritura que nosotros debemos  cumplir  es el plan divino. Lo que así está escrito es siempre lo mejor para nosotros y no podemos hacer nada mejor que orientarnos por él',
    'Debemos descubrir siempre la voluntad de Dios interpretando los tiempos, las dificultades de la época. Es nuestro modo de ser  no huir ante las dificultades, sino, al contrario, interpretar las dificultades de los tiempos como tareas querida por Dios para el tiempo. Es ésta la fe en la Divina Providencia aplicada concretamente',
    'Educar significa servir a Cristo en los hombres como lo hizo María',
    'Educar significa servir desinteresadamente a la singularidad y originalidad del prójimo',
    'Educar significa: acoger vida, despertar vida y transmitir vida',
    'Cuenten con fracasos. Deben tomarlos como algo sobreentendido. Los fracasos en la educación significan el mayor éxito para nosotros',
    'Estos fracasos nos vuelven pequeños. Son para nosotros escuela. El fracaso convierte al sembrador en semilla',
    'El que quiera educar hombres nobles y puros ha de darse a ellos en forma noble y pura',
    'Buscamos que el Espíritu Santo influya en nuestra vida y, reflejándose en nosotros, nos regale  el milagro de la purificación de nuestros instintos y de la conversión interior',
    'Cuando el Espíritu Santo actúa en el alma de un modo profundamente eficaz, entonces el hijo tiene un solo ideal: cumplir el deseo del Padre, vivir en conformidad con la voluntad de Dios',
    'Haz que la luz del Espíritu Santo me ilumine, y mire con fe como el amor del Padre me acompañó en este día',
    'El espíritu de la familia no pregunta: ¿qué recibo yo? Solo vive del pensamiento: ¿qué puedo y debo regalar?',
    'Quien sirve desinteresadamente, reina',
    'Quien da hogar a otros, lo encuentra',
    'Transfórmese en hogar para muchos',
    'La filialidad es la perfecta sencillez',
    'La filialidad confiere la fuerza de soportar en forma adecuada todos los estados de angustia y -en parte- también de vencerlos',
    'Puedo alabar de muchos modos a una persona, pero mi máximo elogio consiste en decirle que ha permanecido fiel',
    'La Santísima Virgen es el modelo de la auténtica filialidad. Ella la aprendió del Hijo de Dios',
    '¡Vive las pequeñas virtudes! ¡Vive tu ideal personal! ¡Ve por el camino de la filialidad! ¡Elige el sendero de la pequeñez!',
    'Cuanto más filialmente me comporte con Dios, tantas más riquezas volcará Él en mi alma',
    'Para que amargarse con preocupaciones que dañan la filialidad',
    'Hay que aprender  a pronunciar  un sí alegre en todas las situaciones',
    'Quien permanece fiel a la herencia, será fecundo de Generación en Generación',
    'Manténganse fielmente  unidos y no olviden: ¡El amor supera todo!',
    'Lo que hoy salva al mundo es un gran desprendimiento, es el espíritu de sacrificio, y éste debe nacer del amor filial',
    'El profundo amor filial enciende un desprendimiento increíble',
    'La impotencia supone una vinculación más profunda y estrecha con la gracia',
    'La gracia debe ser implorada con oraciones y sacrificios',
    'Un líder debe ser una persona que está con la mano en el pulso del tiempo y el oído en el corazón de Dios',
    'Forjen un hombre nuevo en una comunidad nueva con una nueva ética laboral',
    'El verdadero jefe es el hombre de un único y gran ideal',
    'Ama y serás un auténtico jefe',
    '¡Que Jesús reine en nuestro corazón!',
    '¡Jesús! Así como Tú te has consumido y vencido, quiero yo consumirme y vencerme a fin de que Tú seas mi Dios y mi todo',
    'Si amo con todo mi corazón a Cristo, quiero asemejarme a Él. Y si me regala una astillita de su cruz, esto me depara felicidad',
    'Cristo es mi vida y morir una ganancia',
    'Cuando Cristo se encontraba frente a acontecimientos importantes, se retiraba noches enteras para orar',
    'La actitud básica de Cristo fue siempre la misma: «Padre, no se haga mi voluntad sino la tuya»',
    'Donde la lámpara del Santísimo arde y jamás se extingue, se consume nuestra alma para desposarse contigo',
    'Con María, alegres por la esperanza y seguros de la victoria hacia los tiempos más nuevos',
    'María es el alma de mi alma',
    '¡María, que tu vida sea la mía!',
    '¡Aseméjame a ti!',
    'Se para nosotros en todo tiempo, la Madre Tres veces Admirable que resuelve todos los problemas',
    '¡Guíame según tus sabios planes y se cumplirá mi único anhelo!',
    'Debo leer siempre de nuevo en el corazón de María, pues ningún libro aquí en la tierra nos guía más rápido hacia el cielo',
    'Has de mí un pequeño sol para mi alrededor, que irradie luz y calor en todas partes',
    'Elegir a la Madre de Dios como reina de nuestros corazones significa dejar que: “Ella nos modele como cera blanda”',
    'Por María, en Cristo y el Espíritu Santo, al Padre',
    'Tú me has atraído hacia Ti con lazos humanos',
    'Santa Madre imprime profundamente en mi alma las llagas que tu Hijo sufrió por mi causa',
    '¡Sácame de mí mismo y hazme totalmente tuyo!',
    'Madre tres veces Admirable, déjame ser en todo tu instrumento',
    'Pruébenme por hechos que me aman realmente y que toman en serio su propósito',
    'Cuando todo parezca imposible, la Santísima Virgen se glorificará ¡Inmaculada, si yo fuera como Tú!',
    'Santa Madre, haz que las llagas que por mi soportó tu Hijo, se impriman hondamente en mi corazón',
    '¡Que se haga la pequeña María totalmente entregada y abandonada al Padre, a sus deseos y a su voluntad!',
    '¡Que mi vida sea un gran Magnificat!',
    'Que viva en mí el alma de María, para que cante en mí el Magnificat',
    'No hay nada tan semejante a Dios como una mujer noble que, en sencillo autodominio y llena de Dios, posee el auténtico espíritu de libertad interior de los hijos de Dios',
    'El Padre saluda a sus azucenas',
    'Un niño vive para el momento presente',
    'Lo que nos fascina en el niño es especialmente su simplicidad, su rectitud, su sencillez',
    '«La oración es la mayor fuerza educativa en el cielo y en la tierra» (T, 115)',
    'Dios debe tocar nuestro corazón para que realmente aprendamos a orar',
    'Para medir nuestra vida cristiana sólo necesitamos fijarnos cómo rezamos. ¡Con agrado, con alegría, con profundidad, constantemente!',
    'Quien no se domina en el hablar, jamás llegará a poseer un profundo espíritu de oración',
    'Durante el día debemos mantener el contacto con Dios también mediante breves jaculatorias',
    'Debemos procurar que el trabajo llegue a ser oración, y la oración trabajo; en definitiva debemos lograr que ambos confluyan',
    'Recogimiento es reunir todas las fuerzas y concentrarlas en Dios. Rece mucho y póngase las exigencias más altas',
    'Serví y mi reconpensa fue la paz',
    '¿Qué tarea tenía San José? La de cuidar a la Madre y al niño. El tuvo esta tarea y la continúa aún hoy, velando para que la Madre nunca sea separada del Niño',
    'La santidad es lo más sencillo del mundo: es el amor de niño al Padre',
    'El santo de la vida diaria hace todo lo más perfectamente posible pero, ¡Cómo expresión de un íntimo amor!',
    'Dios no solamente quiere que en todas las situaciones digamos “SI”, sino que además lo digamos con una sonrisa, con alegría',
    'Santificar la vida diaria es estar conforme con la voluntad de Dios. ¡Esto en una meta altísima! En ello consiste la santidad',
    'Trinidad Santísima, alabanza a Ti eternamente',
    'Todos los que acudan aquí para orar deben experimentar la gloria de María y confesar: ¡Qué bien estamos aquí! ¡Este es nuestro lugar predilecto!',
    'Como el pájaro ama su nido amo yo mi Santuario',
    '¡El santuario del corazón está consagrado al Dios Trino y habitado por Él!',
    'Y ahora, continuemos trabajando valientemente rezando y sacrificándonos por nuestra ciudad ideal de Schoenstatt, cada uno allí donde está',
    'Schoenstatt: por ti yo vivo. Schoenstatt: por ti yo muero. Schoenstatt: soy tuyo en vida y en muerte',
    '¡Yo, el corazón de ustedes, y ustedes, mi corona! Schoenstatt se ha hecho por el servicio desinteresado a los demás y deberá seguir creciendo de la misma manera',
    'Cada pequeño suceso de nuestra vida es un saludo a Dios',
    'El que quiere ganar los corazones, tiene que poner como prenda su propio corazón',
    'Solamente la fe viva vence al mundo',
    'El servicio a la vida ajena es el servicio a la vida de Cristo en nosotros, el servicio a la vida de Dios, a la vida divina en nosotros',
    'Debemos ser portadores del sonreír divino…aunque la naturaleza llore o se quebrante',
    'Nadie debiera quitarnos la alegría porque Dios, autor del plan de mi vida, es la causa de mi sonrisa y de mi alegría…',
    'Sea usted para muchas personas un indicador de camino, portador de luz y alegría',
    'Todas las dificultades en nuestra vida tenemos que considerarlas como tareas',
    'Haga feliz a cuantas personas le sea posible',
    'La tranquilidad en medio de la desolación es la máxima perfección',
    '…aspirar al desprendimiento de sí mismo y a pasar sencillamente desapercibido…',
    'Tenemos que tener un instinto divino, un gusto divino y una total entrega divina',
    '¡Lo que heredaron de sus padres, luchen para poseerlo!',
    'Solamente al que es respetuoso se le abren las profundidades de la propia alma',
    'Permanezca sencillo, alegre y fiel',
    'Que pueda ser un sol para todos',
    'Cuando soy débil soy fuerte',
    'Hago lo que puedo',
    'Quien sirve desinteresadamente, gobierna',
    'Conserve lo que ha conquistado para que nadie le robe la corona',
    'Sus Ángeles  contemplan permanentemente el rostro del Padre',
    'Lo que vale ante los ojos de Dios es para mi norma de valoración de todas las cosas. Todo lo demás es vanidad y tiene poco valor',
    'Quien sirve desinteresadamente a otros, está en camino hacia la verdadera realeza…',
    'Tranquilidad en el abandono es la máxima perfección',
    'Vuestro andar sea en el cielo en el corazón, en la voluntad y en el mundo de los valores del Padre',
    '¡Revístanse de un corazón lleno de misericordia!',
    '¡No os preocupéis angustiosamente! La mayor preocupación ha de ser: No tener preocupaciones',
    'Es importante que, lleno de confianza, Ud. entregue una gran parte de la responsabilidad a la querida Madre de Dios',
    'Hay que arrancar toda fibra del alma que no pertenezca a Dios',
    'El trabajo es una participación en la actividad de Dios creadora y comunicadora de sí mismo',
    'Todo lo grande crece y madura silenciosamente'
]

export const telRandom = () =>{
    return(tels[Math.floor(Math.random() * tels.length)])
}